--  --  --  --  --
-- TITLE: EXAMPLE SQL CODE
-- DATE: 10/23/2022
-- AUTHOR: S. HERDA
-- EMAIL: SMHERDA@UCDAVIS.EDU
-- SUMMARY: PROVIDES AN EXAMPLE OF USING TABLES IN A DATABASE AND CREATING TABLES. 
--  --  --  --  --

-- DECLARE VARIABLES
DECLARE @TEST_VAR1 VARCHAR(10), @TEST_VAR2 VARCHAR(10), @TEST_VAR3 VARCHAR(10)
DECLARE @SQL_1 VARCHAR(MAX)

-- DROP TABLES
DROP TABLE IF EXISTS ##TT_TEST1   -- TEMP TABLE 1
DROP TABLE IF EXISTS ##TT_TEST2   -- TEMP TABLE 2
DROP TABLE IF EXISTS ##TT_TEST3   -- TEMP TABLE 3

-- GET INFO FROM FIRST TABLE WHERE VALUE_1 IS GREATER THAN 10
SELECT TOP(1) * INTO ##TT_TEST1 
FROM [DATABASE_1].[dbo].[TABLE_1]
WHERE INFO_1 = 'VALUE_1'

-- GET VARIABLE 1 AND VARIABLE 2
SET VAR_1 = (SELECT INFO_1 FROM ##TT_TEST1)
SET VAR_2 = (SELECT INFO_2 FROM ##TT_TEST1)

-- CREATE NEW TABLE WITH PARAMETERS APPLIED
SELECT DISTINCT(INFO_1) INTO ##TT_TEST2
FROM [DATABASE_1].[dbo].[TABLE_1]
WHERE INFO_1 < VALUE_1 AND INFO_2 LIKE '%TEST%'

-- GET INFORMATION FROM JOINED TABLES
SELECT T2.INFO_1, INFO_2 INTO ##TT_TEST2 FROM ##TT_TEST2 T2
RIGHT JOIN [DATABASE_1].[dbo].[TABLE_2] T3
ON T2.INFO_1 = T3.INFO_1

-- CONCATENATE FOR ALL PARAMETERS 
SET @SQL_1 = COALESCE(@SQL_1 + '], [' , '[') + REPLACE(COL_NAMES, '_', '-') FROM [DATABASE_1].[dbo].[COL_NAMES]
SET @SQL_1 = 'SELECT ' + @SQL_1 + '] INTO ##TT_TEST3 FROM [DATABASE_1].[dbo].[TABLE_2]'
EXEC(@SQL_1)
